spring:
  application:
    name: Configuration-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Prudhvi-Teja/ConfigRepository.git
          search-paths:
           - '{application}'
          refresh-rate: 0
        default-label: main
      

server:
  port: 8888

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'